adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: dfe_customerjourneyconfig
adx_entityname: Enquiry/CustomerJourneyConfigGlobalRead
adx_entitypermission_webrole:
- 227532d4-626f-ef11-a670-7c1e522065e3
- 2dadaed1-626f-ef11-a670-002248a430ac
adx_entitypermissionid: c3a94b39-1da1-ef11-8a6a-002248a46a38
adx_read: true
adx_scope: 756150000
adx_write: false
