adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: dfe_enquirycontactconfiguration
adx_entityname: Enquiry/ContactConfigGlobalRead
adx_entitypermission_webrole:
- 2dadaed1-626f-ef11-a670-002248a430ac
adx_entitypermissionid: 54eda33b-5bcf-ef11-b8e9-7c1e521fa723
adx_read: true
adx_scope: 756150000
adx_write: false
