adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: product
adx_entityname: Products
adx_entitypermission_webrole:
- 227532d4-626f-ef11-a670-7c1e522065e3
adx_entitypermissionid: a9ab2ccb-626f-ef11-a670-000d3adb261f
adx_read: true
adx_scope: 756150000
adx_write: false
