adx_append: true
adx_appendto: true
adx_create: false
adx_delete: false
adx_entitylogicalname: dfe_enquirysubcategorylevel1
adx_entityname: Enquiry/SubCatgoryLevel1ConfigGlobalRead
adx_entitypermission_webrole:
- 227532d4-626f-ef11-a670-7c1e522065e3
- 2dadaed1-626f-ef11-a670-002248a430ac
adx_entitypermissionid: 0ce5c1d9-60e5-ef11-8eea-002248999f6b
adx_read: true
adx_scope: 756150000
adx_write: false
