name: Create DfE Power Pages Website

on:
  workflow_dispatch:
    inputs:
      client-id:
        description: 'Client ID'
        required: true
      client-secret:
        description: 'Client Secret'
        required: true
      environment-url:
        description: 'Target Environment URL'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Main branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Authentication Check
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.client-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ secrets.TENANT_ID }}

    - name: Upload DfE Site to Target Environment
      uses: microsoft/powerplatform-actions/upload-paportal@v1
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.client-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ secrets.TENANT_ID }}
        upload-path: "./${{ secrets.DFE_WEBSITE_FOLDER }}"
        model-version: enhanced
