name: Download DfE Portal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check Permissions
      shell: pwsh
      run: |
        $authorizedUsers = "${{ secrets.AUTHORIZED_USERS }}"
        $currentUser = "${{ github.actor }}"
        if ($authorizedUsers -notcontains $currentUser) {
          Write-Output "Error: You do not have permission to run this workflow."
          exit 1
        }
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Authentication Check
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ secrets.POWER_PLATFORM_URL }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
        
    - name: Download GOVUK Portal
      uses: microsoft/powerplatform-actions/download-paportal@v1
      with:
        environment-url: ${{ secrets.POWER_PLATFORM_URL }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
        download-path: .
        website-id: ${{ secrets.DFE_WEBSITE_ID }}
        overwrite: true

    - name: Remove central-* Files
      run: |
        find . -type f -name "central-*" -exec rm -f {} +

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Commit and Push Portal Files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Stage and commit all changes
        git add .
        git commit -m "Added GOVUK portal download for build ${GITHUB_RUN_NUMBER}" || echo "No changes to commit"
        
        # Push changes to the branch from which the workflow was triggered
        git push origin HEAD
        
