name: Download GOVUK Portal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Authentication Check
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ secrets.POWER_PLATFORM_URL }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
        
    - name: Download GOVUK Portal
      uses: microsoft/powerplatform-actions/download-paportal@v1
      with:
        environment-url: ${{ secrets.POWER_PLATFORM_URL }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
        download-path: ./${{ secrets.GOVUK_WEBSITE_NAME}}
        website-id: ${{ secrets.GOVUK_WEBSITE_ID }}
        overwrite: true
        
