name: Download GOVUK Portal

on:
  workflow_dispatch:

jobs:
  portal-actions:
    runs-on: ubuntu-latest

    steps:
    - name: Install Power Platform CLI
      run: |
        wget https://aka.ms/PowerAppsCLI-linux -O pac-linux.tar.gz
        mkdir -p ~/pac
        tar -xzf pac-linux.tar.gz -C ~/pac
        export PATH="$PATH:~/pac"

    - name: Authenticate with Power Platform
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
      run: |
        TOKEN=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&scope=${{ secrets.POWER_PLATFORM_URL }}/.default&grant_type=client_credentials" \
          "https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/token" | jq -r .access_token)
        echo "TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Download GOVUK Portal Files
      env:
        TOKEN: ${{ env.TOKEN }}
        POWER_PLATFORM_URL: ${{ secrets.POWER_PLATFORM_URL }}
      run: |
        pac paportal download --environment ${{ secrets.POWER_PLATFORM_URL }} \
                              --webSiteId ${{ secrets.GOVUK_WEBSITE_ID }} \
                              --path /
